### ISSUE TITLE
LinkedIn  not working

### ISSUE THREAD

**Issue by monikarora** [theappguruz/Android-Linkedin-Connectivity-code-sample#1]
Hey @theappguruz  LinkedIn not working at my end . please check error 

   Process: com.tag.linkedinconnectivity, PID: 29954
                                                                              com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceException: oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: https://api.linkedin.com/uas/oauth/requestToken
                                                                                  at com.google.code.linkedinapi.client.oauth.LinkedInOAuthServiceImpl.getOAuthRequestToken(LinkedInOAuthServiceImpl.java:180)
                                                                                  at com.tag.linkedinconnectivity.MainActivity.onClick(MainActivity.java:62)
                                                                                  at android.view.View.performClick(View.java:5612)
                                                                                  at android.view.View$PerformClick.run(View.java:22285)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                               Caused by: oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: https://api.linkedin.com/uas/oauth/requestToken
                                                                                  at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:214)
                                                                                  at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:69)

**Comment by tpatel27** [comment]
same error .......if any one cam help me with this
